language: objective-c
osx_image: xcode7.3
xcode_workspace: AeroGearSyncClientJsonPatch.xcworkspace
xcode_scheme: AeroGearSyncClientJsonPatch
xcode_sdk: iphonesimulator

before_install:
  - pod repo update

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
script:
  - xcodebuild -workspace AeroGearSyncClientJsonPatch.xcworkspace -scheme AeroGearSyncClientJsonPatch -sdk iphonesimulator build